Add a Swift Playground as an example
google/generative-ai-swift pull request #69
Opened 2023-12-14 22:47 UTC by andrewheard

Added a starter Swift Playground for generating text from a prompt.

2023-12-14 23:09 UTC, peterfriese commented on Examples/GoogleAIPlayground.swiftpm/GenerateTextView.swift
> +  func generateText() {
I think we should rename this to `send` or `sendMessage`, like in the other samples.

2023-12-14 23:12 UTC, peterfriese commented on Examples/GoogleAIPlayground.swiftpm/GenerateTextView.swift
> +        TextField("Enter a prompt...", text: $prompt)
Add an `onSubmit` handler so people can just hit [enter] to send the message.

2023-12-14 23:12 UTC, peterfriese commented on Examples/GoogleAIPlayground.swiftpm/GenerateTextView.swift
> +        Button("Send", systemImage: "arrow.up.circle.fill") {
Use a `Button` with a nested `Image`, like in the other samples

2023-12-14 23:21 UTC, peterfriese requested changes
Great idea, thanks for putting this together!

I found it pretty difficult to edit the text in the Swift Playground app, as the code is formatted using 2 spaces, but the Playground app doesn't seem to allow changing the indentation width. So you constantly end up fighting the editor, which is a pretty bad user experience.

We should change the formatter configuration for this example.

2023-12-15 16:50 UTC, andrewheard commented
Thanks for the review, @peterfriese! Closing this in favour of adding docs instead (#72).

2023-12-15 16:50 UTC, closed without merging